### ISSUE TITLE
GitSource cannot fetch an older commit SHA with --depth=1

### ISSUE THREAD

**Issue by ImJasonH** [knative/build#212]
When `GitSource.Revision` specifies a commit SHA in the repo, the `git-init` image prefixed onto the user-specified build steps ends up calling:

```
git fetch --depth=1 --recurse-submodules=yes origin deadbeef123
```

This seems to cause problems when a.) `origin` is a repo hosted by GitHub, and b.) when the commit SHA in question is not the `HEAD` of a branch.

According to [this SO question](https://superuser.com/questions/1240216/what-does-the-git-error-message-server-does-not-allow-request-for-unadvertised), GitHub doesn't like it when you do a shallow clone (`--depth=1`) of a single commit by its SHA:

> So, if you want to get a specific commit with `--depth`, it must be at most `<depth>-1` commits away from the fetched ref (which is the branch/tag specified in the submodule's metadata)

In my experience, this means that `revision: <some-sha>` works when `<some-sha>` is the `HEAD` of a branch, but not when that branch moves beyond that commit. This manifests in integration test failures in `tests/git-source/1-commit.yaml` since the commit SHA needs to be continually updated to the test repo's tip of master.

## Expected Behavior

```
source:
  git:
    url: https://github.com/foo/bar
    revision: <some-sha>
```

works reliably, so long as the repo contains some commit with that SHA.

## Actual Behavior

The above stanza only works so long as `<some-sha>` is the `HEAD` of a branch.

## Additional Info

This might only be a problem since we `git fetch` with both `--depth=1` and `--recurse-submodules=yes` -- if we fetched them separately, or didn't fetch submodules by default, this might not be a problem.

/cc @wlynch, our resident Git expert.

**Comment by greghaynes** [comment]
I Am Not A Git Expert but per the docs (https://git-scm.com/docs/git-fetch#git-fetch---depthltdepthgt) this seems to be the expected behavior, not just a githubism:

> --depth=<depth> 
> Limit fetching to the specified number of commits from the tip of each remote branch history. ...

Note the "from the tip of each remote branch". Searching around there is some server side support in recent versions for this to work from any named ref but that isn't very helpful here.

AFAICT this means our options are either to perform some kind of deep checkout when a user specifies a sha or require named refs.

**Comment by jchesterpivotal** [comment]
Concourse's `git-resource` has [additional logic for this case](https://github.com/concourse/git-resource/blob/3193e49a351237b6a9ddfcd9e478acf7f1d99997/assets/deepen_shallow_clone_until_ref_is_found_then_check_out).
