### ISSUE TITLE
Bring up code coverage of apis/build to 80%

### ISSUE THREAD

**Issue by jessiezcc** [knative/build#264]
/area test-and-release
/kind doc

Expected Behavior
github.com/knative/build/pkg/apis/build code cover should be 80+%

Actual Behavior
It's at 55.2%.

Steps to Reproduce the Problem
Pls refer to https://testgrid-dot-knative-tests.appspot.com/knative-build#coverage for up-to-date CC numbers

Additional Info

**Comment by ImJasonH** [comment]
Coverage now at 92%
