### ISSUE TITLE
Bring up code coverage of webhook to 80%

### ISSUE THREAD

**Issue by jessiezcc** [knative/build#266]
/area test-and-release
/kind doc

Expected Behavior
github.com/knative/build/pkg/webhook code cover should be 80+%

Actual Behavior
It's at 41.6%.

Steps to Reproduce the Problem
Pls refer to https://testgrid-dot-knative-tests.appspot.com/knative-build#coverage for up-to-date CC numbers

Additional Info

**Comment by ImJasonH** [comment]
pkg/webhook was deleted in https://github.com/knative/build/pull/400
