### ISSUE TITLE
Build is not kicking off

### ISSUE THREAD

**Issue by rakyll** [knative/build#281]
Following the instructions on README, after I apply a build.yaml, the output is always:

```
$ kubectl get builds
NAME          KIND
hello-build   Build.v1alpha1.build.knative.dev


$ kubectl describe build
Name:		hello-build
Namespace:	default
Labels:		<none>
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"build.knative.dev/v1alpha1","kind":"Build","metadata":{"annotations":{},"name":"hello-build","namespace":"default"},"spec":{"steps":[{"a...
API Version:	build.knative.dev/v1alpha1
Kind:		Build
Metadata:
  Cluster Name:
  Creation Timestamp:	2018-07-23T18:59:52Z
  Generation:		0
  Resource Version:	3000
  Self Link:		/apis/build.knative.dev/v1alpha1/namespaces/default/builds/hello-build
  UID:			949f66ab-8eaa-11e8-99b7-42010a80007a
Spec:
  Steps:
    Args:
      echo
      hello
      build
    Image:	busybox
    Name:	hello
Events:		<none>
```

The build is never starting.

Note: I don't know the obvious ways (if there are any) to diagnose what went wrong.

**Comment by rakyll** [comment]
Thanks, this was useful! I am running it on GKE and there was an an out-of-memory issue. I expanded my node pool and the build finally saw some progress:

```
$ kubectl get build hello-build -oyaml
...
  conditions:
  - state: Succeeded
    status: "True"
  startTime: 2018-07-23T21:53:38Z
  stepStates:
  - terminated:
      containerID: docker://ce148a3406ea100c24d17b541dd8437d9eb75b44b290ed5b1ea3ee75001f1a02
      exitCode: 0
      finishedAt: 2018-07-23T22:01:27Z
      reason: Completed
      startedAt: 2018-07-23T22:01:27Z
  - terminated:
      containerID: docker://0a731fd5e2225f0caea2ce682220511d985786dd9fc76a425cf65916e9961406
      exitCode: 0
      finishedAt: 2018-07-23T22:01:28Z
      reason: Completed
      startedAt: 2018-07-23T22:01:28Z
```

I still see no AGE for my build:

```
$ kubectl get builds
NAME          KIND
hello-build   Build.v1alpha1.build.knative.dev
```

And more interestingly, my logs seem to be coming from a noop container at https://github.com/knative/build/blob/5d8bfc32e91c175f30046455687fd842a496842e/pkg/builder/cluster/convert/convert.go#L65

```
$ kubectl logs hello-build-4xsw2
Nothing to push
```

**Comment by ImJasonH** [comment]
Steps are executed on the pod as `initContainers` so they run in order, so you need to get logs with `-c build-step-(step-name)`

**Comment by dgageot** [comment]
@rakyll If you `go get -u github.com/knative/build/cmd/logs`, you get the cli tool that'll give you the logs for a build: `logs hello-build`.

If you prefer using only kubectl, then you will have to collect the logs for each `initContainer`.

Also some things are not shown in the logs like when Kubernetes is pulling the images for each step. These can take time and even timeout.
