### ISSUE TITLE
CBI consolidation?

### ISSUE THREAD

**Issue by AkihiroSuda** [knative/build#284]
First of all, huge props to this project :tada:

The project looks very similar to my [CBI](https://github.com/containerbuilding/cbi), which provides a vendor-neutral CRD interface for docker/buildkit/buildah/kaniko/img/gcb/acb/s2i, and I'm wondering whether we can consolidate if we share the goals:

* Is there plan to support non-Google image builders such as BuildKit, S2I, or Azure Container Registry Build as well?
* Is there plan to support non-GCS build context storage?
* Is there plan to donate Knative to a vendor-neutral organization such as Kubernetes SIG[-apps?] or CNCF? Or planned to be permanently owned by Google?

**Comment by ImJasonH** [comment]
Hi @AkihiroSuda :wave: 

We'd love to work with CBI toward a single abstraction for Kubernetes-native container builds.

> Is there plan to support non-Google image builders such as BuildKit, S2I, or Azure Container Registry Build as well?

Absolutely, definitely, 1000%. There are already some non-Google image builders in the [build-templates](https://github.com/knative/build-templates) repo. [buildpacks](https://github.com/knative/build-templates/tree/master/buildpack) were contributed by Pivotal, and there's a [PR to add support for buildah](https://github.com/knative/build-templates/pull/7). We'd gladly accept more. :hugs: 

> Is there plan to support non-GCS build context storage?

Absolutely, definitely, 1000%. When [GCS support was proposed](https://github.com/knative/build/issues/78) we discussed other object storage options, and again, we'd gladly accept proposals to support more. Even GCS's API surface is not set in stone, so we can consider other abstractions for common sources.

If there's something in particular you had in mind I would recommend proposing it as an issue on this repo and maybe bringing it up in the [weekly Build working group](https://github.com/knative/docs/blob/master/community/WORKING-GROUPS.md#build).

> Is there plan to donate Knative to a vendor-neutral organization such as Kubernetes SIG[-apps?] or CNCF? Or planned to be permanently owned by Google?

For that you'd have to ask @mchmarny and @dewitt, but I personally would gladly welcome that, for what it's worth.

**Comment by mchmarny** [comment]
@AkihiroSuda re your CNCF question, we just opened the repos today and are super excited to engage with the larger community. To be honest haven't spend much time thinking out that far yet

**Comment by AkihiroSuda** [comment]
Perfect, thanks!

I'll try to port over CBI features to Knative Build.
