### ISSUE TITLE
test/e2e-tests.sh fails when run locally

### ISSUE THREAD

**Issue by ImJasonH** [knative/build#286]
## Expected Behavior

I can run `./test/e2e-tests.sh` to run end-to-end tests before submitting a PR.

## Actual Behavior

Script creates a cluster, network, firewall rules, etc., then fails due to an unknown flag:

```
2018/07/25 12:09:06 process.go:150: Running: /path/to/go/src/github.com/knative/build/test/e2e-tests.sh --run-tests
Error: unknown flag: --username
```

This seems to come from `library.sh` [here](https://github.com/knative/test-infra/blob/3d555dbb9d4ab2715e6ca227aebc8866a46aa3ac/images/prow-tests/scripts/library.sh#L147), at least that's the only instance of `--username` I could find anywhere in the test-infra repo.

**Comment by adrcunha** [comment]
I can't reproduce, the environment spins up and the tests run as expected. Could it be that we have different `kubectl` versions installed?

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by adrcunha** [comment]
Just saw the line in the log, maybe it's `kubetest`? Mine says:

```
2018/07/27 12:37:10 process.go:153: Running: /usr/local/google/home/adrcunha/go/src/github.com/knative/build/test/e2e-tests.sh --run-tests
clusterrolebinding "cluster-admin-binding" created
```

Can you please try `go get -u k8s.io/test-infra/kubetest`?

**Comment by adrcunha** [comment]
e2e tests aren't running locally anymore (getting from HEAD):

```
Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "system:anonymous" cannot create clusterrolebindings.rbac.authorization.k8s.io at the cluster scope: Unknown user "system:anonymous"
```

**Comment by adrcunha** [comment]
https://github.com/knative/test-infra/pull/87 should have fixed that.

**Comment by adrcunha** [comment]
For the record, 87 is part of the fix, thus 115 was necessary.
