### ISSUE TITLE
Parameter replacement for Volumes

### ISSUE THREAD

**Issue by zhiminwen** [knative/build#296]
## Expected Behavior
When template parameter is replaced with the value, only those under spec.steps are replaced. for example, volumeMounts will be replaced for its parameter value. 

However the ".spec.volumes" which is at the same level of ".spec.steps" is not replaced.

There is some use case when a template define its own volume, for example define a configMap volume to insert updated root certificate to the container.

**Comment by JarreyZhou** [comment]
/assign
please

**Comment by JarreyZhou** [comment]
@zhiminwen , what you mean is to apply replacement to volumes (like replacing configMap's name in volumeSource), so that build can use different configMap just by changing the parameter value.
Am I right in understanding?

**Comment by vdemeester** [comment]
/close
Fixed in #427
