### ISSUE TITLE
Error pushing to Dockerhub with kaniko and Docker secrets

### ISSUE THREAD

**Issue by ImJasonH** [knative/build#313]
Reported in https://twitter.com/chanezon/status/1032788462380834816

Dockerhub secret configured with `stringData`, build with Kaniko fails with cryptic error message:

```
"Error: failed to push to destination http://docker.io/chanezon/knative-app-from-source:latest …: unsupported status code 401; body: 
Usage:
  executor [flags]

Flags:
"
```

@chanezon: Can you share your build configuration, and an outline of your secrets? Sometimes I see this when I forget to specify the `serviceAccountName` in the build, too.

**Comment by jonjohnsonjr** [comment]
Googling the error message turns up this issue as well: https://github.com/GoogleContainerTools/kaniko/issues/290

**Comment by ImJasonH** [comment]
https://twitter.com/chanezon/status/1033105512076734464 seems to indicate the bug was solved, @chanezon when you get a chance please update this issue with your solution, so we can document it better for future users.

Thanks! :+1:

**Comment by chanezon** [comment]
I logged an issue with knative aks install docs https://github.com/knative/docs/issues/358
Not sure if it is related.
