### ISSUE TITLE
question: why not use `kubernetes.io/dockerconfigjson` secret

### ISSUE THREAD

**Issue by AkihiroSuda** [knative/build#389]
## Expected Behavior

I expect `kubernetes.io/dockerconfigjson` (`kubectl create secret docker-registry ...`) could be used as well as [knative-flavored `kubernetes.io/basic-auth`](https://github.com/knative/docs/blob/master/serving/samples/build-private-repo-go/README.md#creating-a-dockerhub-push-credential), so that I don't need to manage two different representations of the same credential

## Actual Behavior

` kubernetes.io/dockerconfigjson` is not supported

## Additional Info

CBI uses `kubernetes.io/dockerconfigjson`  for almost all builders (except GCB and ACB)
https://github.com/containerbuilding/cbi#push-to-a-registry

**Comment by ImJasonH** [comment]
I don't remember a particular discussion about _not_ using that secret type. Off the top of my head it seems doable, though there might be some confusion if you specify a secret of type `kubernetes.io/dockerconfigjson ` and also a secret with `kubernetes.io/basic-auth` annotated for a docker registry -- we'd probably have to decode the config JSON, add the annotated `basic-auth` entry then write the `~/.docker/config.json` in the build context.

Alternatively, if that's too messy, just reject the case where a build service account specifies both types of secrets.

@mattmoor WDYT? Was not supporting `dockerconfigjson` a deliberate decision?

**Comment by AkihiroSuda** [comment]
@mattmoor @vdemeester 

Any thought?

**Comment by AkihiroSuda** [comment]
ping

**Comment by mattmoor** [comment]
Sorry, missed this in the flood.  Supporting that credential type seems fine.

I assume it would key off of the data vs. annotations for deciding the registries to which it applies?

**Comment by AkihiroSuda** [comment]
thanks @vdemeester !
