### ISSUE TITLE
how to locally run the e2e test

### ISSUE THREAD

**Issue by zrss** [knative/build#405]
## Expected Behavior

demonstrates for how to run e2e test locally with **required env**

## Actual Behavior

empty of https://github.com/knative/build/blob/master/test/README.md#environment-requirements

## Additional Info

ref serving part: https://github.com/knative/serving/blob/master/test/README.md#environment-requirements

**Comment by zrss** [comment]
hi @vdemeester , do u know whether environment-requirements of build still work in process ? it seems lack of this part in current docs

**Comment by vdemeester** [comment]
hi @zrss, thanks for the issue : the environment requirements is [there](https://github.com/knative/build/blob/master/test/README.md#environment-requirements), it links to https://github.com/knative/build/blob/master/DEVELOPMENT.md#getting-started. But we may make this text a bit clearer indeed

**Comment by zrss** [comment]
thanks for the reply @vdemeester , i read the docs that u mention and open a PR to add some content base on my practice, could u take a look ?
