### ISSUE TITLE
Question: Why it's called 'build' not 'building' ?

### ISSUE THREAD

**Issue by rhuss** [knative/build#533]
Just a simple question: Why is this project called 'Knative build' and not 'Knative building' to align with 'Knative serving' and 'Knative eventing' (i.e. using the gerund form)

**Comment by assertion** [comment]
Maybe serving and eventing are both continuous actions. Just keep serving or eventing on something. But build is a temporary action and maybe several seconds or minutes, it's done and over.

**Comment by rhuss** [comment]
@assertion Yeah, sounds reasonable. Let me close this issue to reduce the noise, I was just only curious anyway ;-)
