### ISSUE TITLE
logs.Tail blocks if a status has BuildValidationFailed

### ISSUE THREAD

**Issue by poy** [knative/build#579]
## Expected Behavior
`logs.Tail()` exits when an invalid ServiceAccount is used.

## Actual Behavior
`logs.Tail()` blocks when an invalid ServiceAccount is used while trying to find the pod name. 

## Additional Info

Looks like the issue is here:
https://github.com/knative/build/blob/326da2d2747e61f89b627cbde68e2b1d29ea65e3/pkg/logs/logs.go#L230

The reason that is returned is `BuildValidationFailed`, but the condition is only looking for `BuildExecuteFailed`.

**Comment by shashwathi** [comment]
@poy : Thank you for reporting this issue. Submitted PR to fix this.
