### ISSUE TITLE
Can we restart build when the build complete

### ISSUE THREAD

**Issue by zxDiscovery** [knative/build#580]
## Expected Behavior

The `knative/build` can restart the completed build.

## Actual Behavior

I always delete the current complete build and re-apply this build to restart the build in knative.

So I just want to know does the `knative/build` has the feature to restart the build?

/cc @ImJasonH

**Comment by shashwathi** [comment]
@zxDiscovery : There is no restart of build. For restart user has to either delete and apply `knative/Build` or create another Build

**Comment by zxDiscovery** [comment]
@shashwathi , Thanks. Do we have a plan to do a restart feature for build?

**Comment by shashwathi** [comment]
@zxDiscovery : I do not think so. 
cc @ImJasonH

**Comment by ImJasonH** [comment]
No, for now you just have to delete and re-create the build. Pipelines has a plan to enable retries (https://github.com/tektoncd/pipeline/issues/221)
